### ISSUE TITLE
Seeking a video stream

### ISSUE THREAD

**Issue by kicsyromy** [angelcam/rust-ac-ffmpeg#18]
Is there any way to seek within a video stream to a specific frame or timestamp?

As a related question, is there a way to obtain the number of frames or length for a video stream?

Thank you

**Comment by operutka** [comment]
Hi @kicsyromy! The ffmpeg itself supports this. However, this functionality isn't exposed by this crate right now.

We'd need to add a few methods to the `Demuxer`. Feel free to open a pull request if you'd like to help extending this crate. I can point you to the related ffmpeg APIs:
* http://ffmpeg.org/doxygen/4.1/structAVFormatContext.html (the important fields are `start_time`, `duration` and `streams`)
* http://ffmpeg.org/doxygen/4.1/structAVStream.html (the important fields are `time_base`, `start_time`, `duration` and `nb_frames`)
* http://ffmpeg.org/doxygen/4.1/group__lavf__decoding.html#gaa23f7619d8d4ea0857065d9979c75ac8
* http://ffmpeg.org/doxygen/4.1/group__lavf__decoding.html#ga3b40fc8d2fda6992ae6ea2567d71ba30

The biggest challenge here will be probably designing an API that will behave correctly in various situations because seeking and retrieving info about stream length is not supported by all formats. Moreover, even if the format itself supports seeking, it may not be possible to use it because the underlying IO might not be seekable.

**Comment by kicsyromy** [comment]
Hi @operutka

Thanks for the detailed response. I can't promise anything, but I will look into it and try to get a POC going. I'll come back with a PR when I have something that we can discuss on.

Thanks again

**Comment by operutka** [comment]
I believe this can be closed now.
