### ISSUE TITLE
Is there a way to specify native time frame in builder

### ISSUE THREAD

**Issue by mobrine1** [angelcam/rust-ac-ffmpeg#27]
As the title says. I can't seem to find the option to set it using `set_option()`.

In ffmpeg cli, we use `-re` option to do it.

Did try something like:

```
Demuxer::builder()
        .set_option("re", True)
        .build(io)?
```

**Comment by operutka** [comment]
The "re" option is only present in the ffmpeg app. It isn't available in the library. I've never used this option myself, so correct me if I'm wrong. From what I was able to find out, the option makes ffmpeg emulate the native frame rate of the media source. So, for example, if you have a 90 minutes long video, it will take the ffmpeg app 90 minutes to read the video, yielding each packet/frame at the right moment.

You can implement this behavior quite easily yourself:
```rust
use std::time::Instant;

...

let start = Instant::now();

let mut first_dts = None;

while let Some(packet) = demuxer.take()? {
    if let Some(first) = first_dts {
        let delta = packet.dts() - first;
        let elapsed = start.elapsed();
        
        if elapsed < delta {
            std::thread::sleep(delta - elapsed);
        }
    } else {
        first_dts = Some(packet.dts());
    }
    
    // do something with the packet here
}
```

If you're also decoding the packets (e.g. you're implementing a video player), you'll probably want to implement the sleep after the frames get decoded using their presentation timestamps because using packet dts may be inaccurate if there are B frames in your video.

**Comment by mobrine1** [comment]
Yeah, that did the job. As you said. The sleep needs to be added after decoding the packet, doing it in demuxing phase is a bad idea
