### ISSUE TITLE
MP4 muxer memory leak. 

### ISSUE THREAD

**Issue by Lighty0410** [angelcam/rust-ac-ffmpeg#36]
Hey everyone ! 
Recently i tried to remux the live stream from mpegs to fragmented mp4. However, it seems like the ffmpeg mp4 muxer leaks heavily. 
Any tips regarding this issue ? 
Muxer settings - `set_option("movflags", "frag_keyframe"); .set_option("movflags", "empty_moov");`
The reproducable example - https://gist.github.com/Lighty0410/53ab26a7ec028e31b701b2544456dfb4
Valgrind metrics - ![image](https://user-images.githubusercontent.com/29157438/143404920-da9d58e5-4b75-43cb-be17-95879e7e9338.png)

Every suggestion is appreciated. Thanks in advance !

**Comment by operutka** [comment]
Hi @Lighty0410!

What makes you think that this is a leak? It may be simply hidden in reordering buffers or buffers that are used by the MP4 muxer for constructing fragments. Will the memory get released once the muxer is dropped?

I've checked your code and noticed one major issue. You construct your muxer to be able to take all elementary streams from the demuxer but then you filter all packets coming from the demuxer and use only AAC packets. This may be the root cause of your problem. Consider this situation:

1. You have an input stream consisting of 2 elementary streams. Let's say it's h264 and AAC.
2. You construct an fMP4 muxer for all the elementary streams.
3. You give the fMP4 muxer only the AAC packets from the input stream.

The muxer may be simply waiting for packets from the h264 stream to be able to close the fragment. And doing so, it'll have to buffer all other incoming packets. The correct solution would be to create the fMP4 stream only for those elementary streams that will be actually used in the output. And, of course, you'd have to change packet indices accordingly. For example:

1. You have an input stream consisting of 2 elementary streams. Let's say it's h264 (stream index 0) and AAC (stream index 1).
2. You create an fMP4 muxer for the AAC stream (stream index 0).
3. You'll take all packets with stream index 1 coming from the demuxer, change the packet stream index to 0 to match the output and mux them.

I'm also not sure if `frag_keyframe` will work for pure audio streams. Try also `frag_duration`, `frag_every_frame` or `frag_size`.

We use a similar muxer at Angelcam and we don't experience any memory related issues.

**Comment by Lighty0410** [comment]
@operutka 

The thing is. I don't give aac packets only to the muxer. As you may notice, i just filter the AAC packet and if so i apply the bitstream filter. Other than that - i just push other packets directly to the muxer. Here - https://gist.github.com/Lighty0410/53ab26a7ec028e31b701b2544456dfb4#file-leak-rs-L97 . As you can see if it's the AAC packet i apply the bsf. If no - i put the h264 packet directly to the muxer without applying the bitstreamfilter. 

> You have an input stream consisting of 2 elementary streams. Let's say it's h264 (stream index 0) and AAC (stream index 1).
> You create an fMP4 muxer for the AAC stream (stream index 0).
> You'll take all packets with stream index 1 coming from the demuxer, change the packet stream index to 0 to match the output and mux them

 I actually use two elementary streams: h264 and AAC. And it kinda works. I can play the file, push it to the media source extension so force and so on. 
 
 > What makes you think that this is a leak? It may be simply hidden in reordering buffers or buffers that are used by the MP4 muxer for constructing fragments. Will the memory get released once the muxer is dropped?
 
I ran the application for a couple of days. It eats the whole ram (16gb). Just a linear memory growth. I didn't check the memory usage after the demuxer got dropped though.

**Comment by operutka** [comment]
> The thing is. I don't give aac packets only to the muxer. As you may notice, i just filter the AAC packet and if so i apply the bitstream filter. Other than that - i just push other packets directly to the muxer.

Oh, sorry, my bad. I missed this.

> I ran the application for a couple of days. It eats the whole ram (16gb).

I see. As I mentioned, we use a pretty similar code at Angelcam and we certainly don't have any problems with memory. I can only suggest trying a different version of ffmpeg. If it's a bug, then it most likely originates there (based on the snapshot from massif). This library is only a wrapper around the ffmpeg libraries. You can also build your own version of ffmpeg with debug symbols. Maybe you'll be able to better pinpoint the location where these allocations originate.

This is a long shot but I'd also try rewriting the convert function like this:
```rust
fn convert(
    mut demuxer: MpegtsDemuxer,
    mut muxer: Mp4Muxer,
    mut bsf: BitstreamFilter,
    elementary_streams: &[CodecParameters],
) {
    while let Ok(Some(packet)) = demuxer.take() {
        if is_audio_packet(packet.stream_index(), elementary_streams) {
            bsf.push(packet).unwrap();
            while let Ok(Some(packet)) = bsf.take() {
                muxer.push(packet).unwrap();
            }
            continue;
        }

        muxer.push(packet).unwrap();
    }

    muxer.flush().unwrap();
}
```

Even though it should be fine to flush the muxer after every packet, it is a bit unusual. If there is a bug somewhere in the implementation of flush, it would be heavily amplified by flushing the muxer after every packet.

I'd also check that the packets coming from the bitstream filter have correct stream index and timestamps.

**Comment by Lighty0410** [comment]
@operutka 

Got it. Thank you a lot ! I'll try to rebuild ffmpeg with a different version with the debug symbols. Prolly should help. 
Can i keep the issue open for a while ?

**Comment by operutka** [comment]
> Can i keep the issue open for a while ?

Sure. No problem.

**Comment by Lighty0410** [comment]
@operutka
Hey again! Excuse me for the disturbance and raising this issue up again. I just now realized how to try it out. Don't you mind telling me which ffmpeg version do you guys use ? Thanks in advance !

**Comment by operutka** [comment]
No disturbance at all. We're currently using FFmpeg 4.2.4. It's also worth mentioning that we do not use "mp4" as the output format. We use "ismv" instead but that's just a different flavor of MP4, so it uses the same muxer internally.

**Comment by Lighty0410** [comment]
Got it, thank you a lot !

**Comment by Lighty0410** [comment]
@operutka 
Nice! I found the solution and it was really simple :).  `.set_option("movflags", "skip_trailer");` saves the day. No memory leaks/issues whatsoever. Closing the issue. 
Thank you a lot for help!

**Comment by operutka** [comment]
> I found the solution and it was really simple :). `.set_option("movflags", "skip_trailer");` saves the day.

Good to know. Thank you for sharing the solution.
