### ISSUE TITLE
Cannot encode with certain FPS?

### ISSUE THREAD

**Issue by EriKWDev** [angelcam/rust-ac-ffmpeg#41]
Hi! I was trying out the example `examples/encoding.rs`.

When running the sample as is, everything works fine and I get a  black mp4 generated.

However, when I change the line
```rs
let time_base = TimeBase::new(1, 25);
```
into
```rs
let time_base = TimeBase::new(1, 60);
```

I get this error:
```yaml
> cargo run --example=encoding --release out.mp4 -d 100 -w 1920 -h 1080 
[libx264 @ 0x55a81e388140] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
[libx264 @ 0x55a81e388140] profile High, level 4.2, 4:2:0, 8-bit
[libx264 @ 0x55a81e388140] non-strictly-monotonic PTS
[libx264 @ 0x55a81e388140] non-strictly-monotonic PTS
[libx264 @ 0x55a81e388140] non-strictly-monotonic PTS
[libx264 @ 0x55a81e388140] non-strictly-monotonic PTS
[libx264 @ 0x55a81e388140] non-strictly-monotonic PTS
[libx264 @ 0x55a81e388140] non-strictly-monotonic PTS
[libx264 @ 0x55a81e388140] non-strictly-monotonic PTS
[libx264 @ 0x55a81e388140] non-strictly-monotonic PTS
[libx264 @ 0x55a81e388140] non-strictly-monotonic PTS
[libx264 @ 0x55a81e388140] non-strictly-monotonic PTS
[libx264 @ 0x55a81e388140] non-strictly-monotonic PTS
[libx264 @ 0x55a81e388140] non-strictly-monotonic PTS
[libx264 @ 0x55a81e388140] non-strictly-monotonic PTS
[libx264 @ 0x55a81e388140] non-strictly-monotonic PTS
[libx264 @ 0x55a81e388140] non-strictly-monotonic PTS
[libx264 @ 0x55a81e388140] non-strictly-monotonic PTS
[libx264 @ 0x55a81e388140] non-strictly-monotonic PTS
[libx264 @ 0x55a81e388140] non-strictly-monotonic PTS
[libx264 @ 0x55a81e388140] non-strictly-monotonic PTS
[libx264 @ 0x55a81e388140] non-strictly-monotonic PTS
[libx264 @ 0x55a81e388140] non-strictly-monotonic PTS
[libx264 @ 0x55a81e388140] non-strictly-monotonic PTS
[libx264 @ 0x55a81e388140] non-strictly-monotonic PTS
[mp4 @ 0x55a81e7d0a00] Application provided invalid, non monotonically increasing dts to muxer in stream 0: -1500 >= -1500
[libx264 @ 0x55a81e388140] frame I:1     Avg QP:12.00  size:  1151
[libx264 @ 0x55a81e388140] frame P:1     Avg QP:11.00  size:    71
[libx264 @ 0x55a81e388140] mb I  I16..4: 100.0%  0.0%  0.0%
[libx264 @ 0x55a81e388140] mb P  I16..4:  0.0%  0.0%  0.0%  P16..4:  0.0%  0.0%  0.0%  0.0%  0.0%    skip:100.0%
[libx264 @ 0x55a81e388140] 8x8 transform intra:0.0%
[libx264 @ 0x55a81e388140] coded y,uvDC,uvAC intra: 0.0% 0.0% 0.0% inter: 0.0% 0.0% 0.0%
[libx264 @ 0x55a81e388140] i16 v,h,dc,p: 99%  0%  1%  0%
[libx264 @ 0x55a81e388140] i8c dc,h,v,p: 100%  0%  0%  0%
[libx264 @ 0x55a81e388140] Weighted P-Frames: Y:0.0% UV:0.0%
[libx264 @ 0x55a81e388140] kb/s:586.56
ERROR: Invalid argument
```

Setting it to 30, 100 and some other values works fine, but 60 and 120 does not work and produce the above error.

I run on Fedora 36 with `ffmpeg-devel-5.0.1-3.fc36.x86_64` and `x264-0.163-6.20210613git5db6aa6` installed together with rust version `1.61.0` and `ac-ffmpeg = "0.17.4"`.

**Comment by operutka** [comment]
Thanks for spotting this. The example certainly isn't perfect. The purpose of the example is to give people an idea how to use the library, it doesn't aim to be robust.

The main problem here comes from rounding. The frames use time base of 1/1000000 unless you specify a different one. If you change the encoder time base from 1/25 to 1/60 then the timestamps of the first two frames will be 0 and 16666 (that's 0 and 1 scaled from 1/60 time base to 1/1000000, i.e. the default time base for frames). When these frames are passed to the encoder, their timestamps need to be scaled from their time base (i.e. 1/1000000) to the time base of the encoder (i.e. 1/60), this will give you timestamps 0 and 0 (= 16666 * 60 / 1000000). This will create a non-strictly-monotonic sequence of timestamps which is not allowed by the MP4 muxer.

As you can see, the problem comes from the fact that 1/1000000 cannot be divided by 1/60 without a remainder, so scaling timestamps from 1/60 to 1/1000000 and vice versa inevitably leads to rounding errors.

There are many ways how to deal with a problem like this depending on the application. Here we can fix it quite easily by simply changing the time base of the frames. We can simply use the same time base for frames and the encoder.

**Comment by EriKWDev** [comment]
Nice! Makes sense. Thanks for the detailed answer. I suspected the issue was related to rounding.

Would it be out of scope for the library to do a check somewhere wether the time-bases are compatible?

**Comment by operutka** [comment]
> Would it be out of scope for the library to do a check somewhere wether the time-bases are compatible?

Yes, I'm afraid that would be out of the scope.

First, we don't want to add unnecessary overhead. This library is supposed to be a thin wrapper providing a safe interface to FFmpeg. The FFmpeg itself already has the necessary checks in place and emits errors/warnings whenever you construct a non-strictly-monotonic timestamp sequence.

Second, it'd be hard to define what it means that two time bases are incompatible. It's actually quite common to scale timestamps between two time bases where one is not divisible by the other. You just need enough precision to make the rounding errors negligible. Consider the following example.

Let's say you have two time bases 1/90000 and 1/1000000. These time bases are not divisible by each other and yet they provide enough precision for representing timestamp sequences for 60 fps videos. If you wanted to create a timestamp sequence for a 60 fps video in the 1/90000 time base, you'd be incrementing the timestamp by 1500 for each frame. That would give you 0/90000 = 0/60, 1500/90000 = 1/60, 3000/90000 = 2/60, etc. If you convert this sequence into the 1/1000000 time base, you'll get 0/1000000, 16666/1000000, 33333/1000000, etc. After converting it back into the 1/90000 time base, you'll get 0/90000, 1499/90000, 2999/90000, etc. The absolute timestamp error imposed by this conversion would be ~11.1 microseconds which is quite negligible given the fact that you'll most likely see much higher errors during video playback (mostly caused by the display pipeline).
