### ISSUE TITLE
How to encode raw audio data?

### ISSUE THREAD

**Issue by JSDurand** [angelcam/rust-ac-ffmpeg#43]
Hello: 

I am trying to generate some audio file programmatically, like from floats, but I don't know how to encode raw audio data.

For example, say I have generated a sequence of floats `data : Vec<f64>`, how do I encode it and save it to a file?

From my glances in the examples and codes, I think I need to convert the floats into `Packet`s, which can be written to files directly.  And to convert into `Packet`s, I think I have to use an encoder in the following way:

1. Create a new encoder with the correct parameters.
2. Feed the encoder with frames by the `push` method.
3. Take the encoded packets out by the `take` method.

---

Then I have to convert the floats into frames to feed the encoder.  For this, I think I can either

1. Create a new `PacketMut` by the function `PacketMut::new` with the necessary length.
2. Change the packet's data by mutating the individual elements of the mutable slice obtained from the function `PacketMut::data_mut`.
3. Feed the resulting packets to a decoder, probably with some sort of "raw codecs".
4. Take the frames out of the decoder.

or 

1. Create a silent frame by the function `AudioFrameMut::silence`.
2. Somehow alter the contents of the resulting silent frame, which I don't know how to do.

---

**Are the above two ideas the intended way to encode raw audio data?**

Or is there another better, or more idiomatic, way to do so?

Thanks for your good package.  Sorry if this question is ignorant.  I have written what I want to do in C before, but I want to try it in Rust this time.  :)

**Comment by operutka** [comment]
Hi @JSDurand. If you've written this in C before then I assume that you already have a previous experience with FFmpeg. Given this, you probably know that in order to generate and encode audio, you need to:

1. generate audio frames,
2. encode your audio frames using an audio encoder,
3. take packets generated by the audio encoder and mux them into a resulting container.

The entry point for generating your audio frames will really be `AudioFrameMut::silence`. This method will generate an "empty" audio frame. It will allocate a buffer for audio samples and it will fill the buffer with silence to avoid having an uninitialized audio frame. The method uses `av_frame_get_buffer` and `av_samples_set_silence` under the hood (see https://github.com/angelcam/rust-ac-ffmpeg/blob/master/src/codec/frame.c#L52).

In order to put your own audio samples into the audio frame, you'll need to access the planes of the frame (`AudioFrameMut::planes_mut`). The `PlanesMut` type is essentially a slice of planes. There will be one or multiple planes depending on the sample format that you're using. For interleaved sample formats, there will be always only one plane regardless of the number of channels. For planar sample formats, there will be one plane for each audio channel. Each plane then has direct access to a portion of the underlying buffer (using the `Plane::data_mut` method).

You can then write your samples into the corresponding planes. If you're going to write your samples one by one, you can use traits from the `bytes` crate (see https://docs.rs/bytes/1.2.1/bytes/trait.BufMut.html). Just pay attention to endianity. You can also transform the plane data into a slice of samples using a bit of unsafe code. For example:

```rust
let plane: Plane;
let data: &[u8] = plane.data_mut();
let samples: &[f32] = unsafe {
    std::slice::from_raw_parts_mut(data as *mut u8 as *mut f32, data.len() / std::mem::size_of::<f32>())
};
```

Note that the types are there just for illustration. In future versions of this crate, the `Plane` type will be generic over a sample type and there will be methods for accessing the samples rather than methods for accessing the frame buffer, so the unsafe code won't be necessary.

Once you construct your audio frames, you'll need to encode them and mux them. You should find what you need in the code examples (https://github.com/angelcam/rust-ac-ffmpeg/tree/master/examples). The encoding example shows how to encode video but audio is just analogous.

I hope this will help you. If you have any other questions, let me know.

**Comment by JSDurand** [comment]
Thanks a lot.

I now understand how to do it.  I will try it out in the near future.

You can close this issue if you want.  

Thanks again. 😺
