### ISSUE TITLE
Zero-overhead abstraction?

### ISSUE THREAD

**Issue by harrynull** [angelcam/rust-ac-ffmpeg#47]
I think the abstractions are great but it seems that you have to clone / allocate the frame buffer for every frame you want to encode. Is there a way that lets you reuse a buffer, or even modify the ffmpeg's internal data pointer to our existing buffer so you don't have to do any copying?

`Encoder` takes a `VideoFrame` and the freeze method of `VideoFrameMut` consumes/moves it which prevents me from reusing it. Is there a reason for this design?

Thank you for making the library open-source!

**Comment by operutka** [comment]
Hi @harrynull and thank you for your feedback.

I'm not sure what exactly is your use case but let me ensure you that cloning audio/video frames is quite cheap. FFmpeg uses reference-counted buffers internally, so cloning a frame typically won't copy any data. There used to be some edge cases because not all decoders were allocating frame buffers as reference-counted but it should be quite rare these days.

So if you're, for example, using a typical transcoding pipeline (i.e. demux -> decode -> encode -> mux), then there won't be really too much of data copying. There might be something inside the FFmpeg itself but there shouldn't be anything in our abstraction.

If you're using a pure encoding pipeline (i.e. generate a frame -> freeze -> encode -> mux), then you also don't have to copy any data. You can generate your frames using `AudioFrameMut`/`VideoFrameMut` and write the frame data directly into the frame planes. Reusing a frame for repeated encoding might not be possible because your encoder might buffer the frame internally (keep reading for more info).

The only use case that isn't properly covered is the one where you already have existing audio/image data and you need to modify the data before encoding it (e.g. a pipeline like demux -> decode -> modify -> encode -> mux). There is a mechanism for it but we've haven't implemented it for frames yet. It's a similar mechanism to what you can already find in the implementation of `Packet`/`PacketMut` (see https://docs.rs/ac-ffmpeg/0.17.4/src/ac_ffmpeg/packet.rs.html#340-355).

The reason why we have `Packet`/`PacketMut`, `AudioFrame`/`AudioFrameMut` and `VideoFrame`/`VideoFrameMut` is the same as for `Bytes`/`BytesMut` that you can find in the `bytes` crate. The type system ensures that there is only one copy of a mutable frame/packet. Then if you transform your frame/packet into the immutable version, you can easily create cheap copies without copying the frame/packet data. The reverse transformation from immutable to mutable is a bit tricky because there might be multiple copies of your immutable frame/packet sharing the same data. The `Packet::into_mut()` method implements this by copying the packet data only if there is more than one copy of the packet.

The concept of frame/packet immutability is important here because decoders, encoders and muxers can use internal queues for incoming frames/packets. If you were, for example, allowed to modify a frame after passing it to an encoder, then the encoder output would be unpredictable because you could be modifying a frame that hasn't been encoded yet.

If you'd like to implement the `into_mut` method also for `AudioFrame` and `VideoFrame`, feel free to open a pull request.

**Comment by harrynull** [comment]
Thank you for your quick and detailed response!

To give some more context, my use case is screen capturing and then streaming with WebRTC (so I don't need mux from ffmpeg).

> You can generate your frames using AudioFrameMut/VideoFrameMut and write the frame data directly into the frame planes.

Due to system API limitations it's not always possible to do that. d3d's `Map` only gives a pointer to an existing buffer.

> Reusing a frame for repeated encoding might not be possible because your encoder might buffer the frame internally

I'm not super familiar with ffmpeg's implmentation so I didn't know about this behavior. I wonder if it is dependent on the specific encoder I use. I actually did some hacking and it appears to be fine to reuse the frame. Is there a way to prevent this buffering or to know if the frame is being buffered? In that case I could preallocate say 2 frames and alternately use them.

I did some quick benchmarking and it seems that
* allocation of a 4K frame takes 4ms
* copying takes 2ms
* the actual encoding takes 4ms

We only have 16ms for the entire capture - encode - stream process to achieve 60fps, so I don't really want to afford 6ms just to allocate and copy buffer unless absolutely necessary.

I wonder if `into_mut` (which I guess internally call `av_frame_make_writable`) would help in this case (could it detect if frame is being buffered and safely reuse the frame?)

**Comment by harrynull** [comment]
I was also looking into `avcodec_alloc_frame` and `av_image_fill_arrays`. It seems that they might be doing what I want.

**Comment by operutka** [comment]
> We only have 16ms for the entire capture - encode - stream process to achieve 60fps, so I don't really want to afford 6ms just to allocate and copy buffer unless absolutely necessary.

I see.

> the actual encoding takes 4ms

That's quite impressive. Is it H.624? I guess you must be using some really powerful HW encoder to achieve this.

> I wonder if it is dependent on the specific encoder I use. (...) Is there a way to prevent this buffering or to know if the frame is being buffered?

This may depend on a lot of things. It is both codec and encoder specific and it may also depend on encoding profile, preset and and the encoding schema. There is no reliable way how to tell how deep your encoding queue is. At least not directly. It may also change with FFmpeg or driver updates. Encoders typically need to buffer a few frames if B frames are being used to improve compression ratio. But it isn't the only case.

> I actually did some hacking and it appears to be fine to reuse the frame.

I wouldn't count on that.

> I wonder if into_mut (which I guess internally call av_frame_make_writable) would help in this case (could it detect if frame is being buffered and safely reuse the frame?)

That's precisely the purpose of this method. Or at least partially. The method would be useless if the encoder have buffered any frames. In such case, the method would end up allocating a new frame and you'd be right where you are now.

The FFmpeg documentation says the following:

_Ownership of the frame remains with the caller, and the encoder will not write to the frame. The encoder may create a reference to the frame data (or copy it if the frame is not reference-counted)._

In other words, the encoder may create an internal copy of the frame data. This is cheap with reference-counted buffers that are being used by default but if the encoder does create a copy and you then try to make the frame writable again using `av_frame_make_writable`, the function will allocate a new buffer for the frame data. It would be also pointless to create frames directly from the buffer received from d3d because the encoder could easily end up creating a copy of the data. Not mentioning potential safety issues because FFmpeg requires the frame data to be properly aligned for each line of the image.

I'd propose the following solution:

1. Let's implement a method called `try_into_mut` for `VideoFrame` and `AudioFrame`. This method would have the following signature:

   ```rust
   pub fn try_into_mut(mut self) -> Result<VideoFrameMut, VideoFrame> { ... }
   ```

   It could be implemented with a little help from the `av_frame_is_writable` function.

2. This would allow you to create a pool of reusable frames. Something like this:

   ```rust
   struct FramePool {
       frames: VecDeque<VideoFrame>,
   }

   impl FramePool {
       /// Put a given frame back to the pool after it was used.
       fn put(&mut self, frame: VideoFrame) {
           self.frames.push_back(frame);
       }

       /// Take a writable frame from the pool or allocate a new one if necessary.
       fn take(&mut self) -> VideoFrameMut {
           if let Some(frame) = self.frames.pop_front() {
               match frame.try_into_mut() {
                   Ok(frame) => return frame,
                   Err(frame) => self.frames.push_front(frame),
               }
           }

           VideoFrameMut::black(...)
       }
   }
   ```

3. You could then use the pool knowing that the number of frames in the pool would eventually match the depth of the input queue of your encoder. This will help you to shave off those 4 ms for the frame allocation and initialization but those 2 ms for copying the frame data would be still needed.

**Comment by harrynull** [comment]
> That's quite impressive. Is it H.624? I guess you must be using some really powerful HW encoder to achieve this.

Yes, it's H264 and nvenc with low-latency preset.

> This may depend on a lot of things. It is both codec and encoder specific and it may also depend on encoding profile, preset and and the encoding schema.

That makes sense!

> I'd propose the following solution:

That is precisely what I was thinking. I will try to implement that and then perhaps make a PR. Thank you so much for your help.
