### ISSUE TITLE
Upon closing muxer - "Error number 67 occurred" (ENOLINK 67 Link has been severed)

### ISSUE THREAD

**Issue by KingOfTheBlues** [angelcam/rust-ac-ffmpeg#59]
Hello, I'm hopeful this is something simple in my environment that someone else has encountered!

Recently I have gone from a working setup in Ubuntu 18.04.

Now in Ubuntu 22.04, when calling close on a muxer at the end of a demux, decode, encode and mux pipeline (which completes), I have the following error returned: **"Error number 67 occurred"**.

Looking through the ffmpeg source, this is not a mapped error code and appears to come from libc or if not another source unknown to me. Running "errno 67" returns **"ENOLINK 67 Link has been severed"**.

I have the below packages at version 4.4.2-0ubuntu0.22.04.1:
- libavutil-dev (libavutil.so.56.70.100)
- libavcodec-dev (libavcodec.so.58.134.100)
- libavformat-dev  (libavformat.so.58.76.100)
- libswresample-dev (libswresample.so.3.9.100)
- libswscale-dev (libswscale.so.5.9.100)

I have the build-essential package installed at version 12.9ubuntu3.

Spent a while scratching my head on this any help at all is massively appreciated. Any more info I can supply please let me know.

**Comment by operutka** [comment]
I can only speculate why exactly you get this error. If you post here a minimum working example to reproduce the problem, we can try to analyze it.

Regarding the error code itself - I've never really got this particular error code, so I'm not entirely sure what can be the root cause of it. Based on the comment in `errno.h`, I'd guess it has something to do with a broken link. Maybe your muxer is writing its output into a file behind a symbolic link and the link is no longer valid by the time you try to close the muxer?

**Comment by KingOfTheBlues** [comment]
thanks for the reply, my pipeline is not file based which may be part of the issue, perhaps there is a missing lifetime specifier somewhere. I'm using a docker container for now to proceed but may come back to investigate further and contribute back

**Comment by KingOfTheBlues** [comment]
this was certainly something environmental, never figured out what exactly though

use the sources that come with your OS if possible, or if you must compile ffmpeg by hand do it in a docker container to avoid issues like this
