### ISSUE TITLE
mismatch in actual width and line_size causing encoder to return jumbled output

### ISSUE THREAD

**Issue by Pranav2612000** [angelcam/rust-ac-ffmpeg#78]
Creating a `black` VideoFrameMut ( https://docs.rs/ac-ffmpeg/latest/ac_ffmpeg/codec/video/frame/struct.VideoFrameMut.html#method.black ) of width: 1200 and height: 800 with `libx264rgb` as the encoder and pixel_format as `rgb24` results in a frame having line_size of `1216`. The data buffer is also greater than expected ( 2918400 instead of 2880000 ). This results in the encoding to fail ( or if by some workaround, I'm able to get the video to compile, it appears distorted ).

What's the best way to handle these differences?

If I capture at 1216 by 800. Everything works as expected.

**Comment by operutka** [comment]
That's a correct behavior. Actually, the line size is supposed to be 3648 bytes (1216 pixels, each pixel is 24 bits). In any case this crate is just a wrapper over FFmpeg libraries. The frame allocation itself is done using `av_frame_get_buffer` which calculates the buffer size and line size based on the target frame width, height and pixel format (more details [here](https://ffmpeg.org//doxygen/5.1/group__lavu__frame.html#ga6b1acbfa82c79bf7fd78d868572f0ceb)).

Line size is usually larger than the actual frame width because some video encoders require the line buffers to be correctly aligned. All video encoders available via the FFmpeg API (even third party libraries) can handle this and some even require it. If you are using a third party encoder directly (i.e. not via the FFmpeg API), you'll need to adjust the code to take this into account. It all depends on the library. There is no general advice.

When you fill the video frame with image data, you also need to take the line size into account. If you copy the image data from another buffer where the stride (or line size) is different, you can't simply copy the image data as it is into the plane and expect that everything will be fine. It would produce a distorted frame (as you mentioned). Usually, you need to copy the image data line by line. The code could look like this:

```rust
fn fill_rgb24_frame(mut input: &[u8], width: usize, height: usize, stride: usize, frame: &mut VideoFrameMut) {
    let plane = &mut frame.planes_mut()[0];

    // we need the width in bytes
    let w = width * 3;

    assert!(stride >= w);
    assert!(plane.line_size() >= w);
    assert!(plane.line_count() >= height);

    for y in 0..height {
        plane
            .line_mut(y)
            .unwrap()[..w]
            .copy_from_slice(&input[..w]);

        input = &input[stride..];
    }
}
```

The asserts are there mostly for you to understand the invariants.

**Comment by Pranav2612000** [comment]
@operutka 
Got it! Thank you!
I read the ffmpeg source code as well but couldn't figure out where the extra buffer was being added.

In any case, this is how I've done it [ For anyone else stumbling on this issue ]
```
                let mut data_ptr: usize = 0;
                let line_size_to_be_written = (frame.width * 3) as usize;
                for mut line in new_frame.planes_mut()[0].lines_mut() {
                    let _ = line.write(&frame.data[data_ptr..(data_ptr + line_size_to_be_written)]);
                    data_ptr += line_size_to_be_written;
                }
```

Do you think this is as good as the solution you suggested?
Also do you think there's a performance hit to copying the data line by line rather than all at once? ( Should we only do a line by line copy if the line-size and the width don't match ?


Thanks for all your help and for maintaining this library

**Comment by operutka** [comment]
> Do you think this is as good as the solution you suggested?

I suppose it's good. Provided that the source `frame` has the same height as `new_frame` and the source `frame` stride is equal to the frame width times 3.

> Also do you think there's a performance hit to copying the data line by line rather than all at once?

Slice `write` and `copy_from_slice` get both optimized down to a `memcpy` call. Performance wise there really isn't much of a difference between a single `memcpy` call to copy 2880000 bytes or 800 `memcpy` calls to copy 3600 bytes. It all depends on the target CPU architecture but, generally, I wouldn't be worried about any performance impact if the line size is 512 bytes or more. And if it's less than 512 bytes then the overall frame size is usually too small to be worried about performance at all.

You can benchmark it if you want. That would probably give you a better answer. In any case, filling the frame with image data does not really cost much compared to video encoding.

> Should we only do a line by line copy if the line-size and the width don't match ?

I wouldn't worry about it. Copying image data line by line is quite common. The FFmpeg does the same thing internally: https://ffmpeg.org//doxygen/6.0/imgutils_8c_source.html#l00344
